sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-system-dev
    - libboost-thread-dev
    - python-dev
    - python-nose
    - python-numpy
    - cmake
    - bison
    - flex
language: python
python:
  - "2.7"
  - "3.4"
env:
  - PROF=deb7
  - PROF=deb8
install:
 - pip install -r requirements-${PROF}.txt
 - mkdir build
 - (cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE -DPYTHON_EXECUTABLE=`which python` -DNEED_PYTHON=ON ..)
 - make -C build -j2 VERBOSE=1
script: make -C build -j2 VERBOSE=1 test
after_failure: cat build/Testing/Temporary/LastTest.log
matrix:
  exclude:
  - python: "3.4"
    env: PROF=deb7
