sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-system-dev
    - libboost-python-dev
    - python-dev
    - python-nose
    - python-numpy
    - cmake
    - bison
    - flex
install:
 - mkdir build
 - (cd build && cmake -DPYTHON_EXECUTABLE=`which python2.7` ..)
 - make -C build -j2 VERBOSE=1
script: make -C build -j2 VERBOSE=1 test
after_failure: sed -e 1,/nosetest/d build/Testing/Temporary/LastTest.log
matrix:
  exclude:
  - python: "3.4"
    env: PROF=deb7
